/* HH Teams V3.2: division and team setup only. Retains V3.0/V3.1 data and rosters. */
'use strict';
const KEY='hh-teams-program-v30', $=id=>document.getElementById(id), clean=v=>String(v||'').trim();
const escape=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
let db;try{db=JSON.parse(localStorage.getItem(KEY)||'null')||{program:'',divisions:[],teams:[]};if(!Array.isArray(db.divisions)||!Array.isArray(db.teams))throw Error('Invalid')}catch(e){db={program:'',divisions:[],teams:[]}}
let current='';
function save(msg='Saved on this device.'){try{localStorage.setItem(KEY,JSON.stringify(db));$('status').textContent=msg}catch(e){$('status').textContent='Unable to save on this device.'}}
const team=()=>db.teams.find(t=>t.id===current);
function render(){let selected=$('quickDivision').value;$('program').value=db.program||'';$('quickDivision').innerHTML=db.divisions.map(d=>`<option value="${escape(d.id)}">${escape(d.name)}</option>`).join('');if(db.divisions.some(d=>d.id===selected))$('quickDivision').value=selected;
$('divisionList').innerHTML=db.divisions.map(d=>`<div class="group"><div class="group-head"><strong>${escape(d.name)}</strong><button class="secondary mini" data-rename-division="${escape(d.id)}">Edit</button><button class="danger mini" data-delete-division="${escape(d.id)}">Delete</button></div>${db.teams.filter(t=>t.division===d.id).map(t=>`<div class="team-item"><strong>${escape(t.name)}</strong><button class="secondary mini" data-manage="${escape(t.id)}">Edit team</button><button class="danger mini" data-delete-team="${escape(t.id)}">Delete</button></div>`).join('')||'<p class="muted">No teams yet. Add one above.</p>'}<button class="mini" data-add-team="${escape(d.id)}">+ Add team</button></div>`).join('')||'<p class="muted">No divisions yet. Create one above.</p>';
renderTeam();}
function renderTeam(){let t=team();$('teamTools').classList.toggle('hide',!t);if(!t)return;$('editingTeamTitle').textContent='Edit '+t.name;$('editTeamName').value=t.name;$('moveDivision').innerHTML=db.divisions.map(d=>`<option value="${escape(d.id)}">${escape(d.name)}</option>`).join('');$('moveDivision').value=t.division;}
$('saveProgram').onclick=()=>{db.program=clean($('program').value);save('Program name saved.');render()};
$('createDivision').onclick=()=>{let name=clean($('divisionName').value);if(!name)return alert('Enter a division name.');if(db.divisions.some(d=>d.name.toLowerCase()===name.toLowerCase()))return alert('That division already exists.');let id=uid();db.divisions.push({id,name});save('Division saved. You can add teams or another division.');$('divisionName').value='';render();$('quickDivision').value=id;};
$('createTeam').onclick=()=>{let division=$('quickDivision').value,name=clean($('teamName').value);if(!db.divisions.some(d=>d.id===division))return alert('Create a division first.');if(!name)return alert('Enter a team name.');db.teams.push({id:uid(),division,name,roster:[],coaches:[],lineup:{label:'',date:'',text:''}});save('Team saved. Add another team or division.');$('teamName').value='';render();$('quickDivision').value=division;};
$('addAnotherDivision').onclick=()=>{$('divisionName').focus();$('divisionName').scrollIntoView({behavior:'smooth',block:'center'})};
$('divisionList').onclick=e=>{let el=e.target,id;if(id=el.dataset.addTeam){$('quickDivision').value=id;$('teamName').focus();$('teamName').scrollIntoView({behavior:'smooth',block:'center'})}else if(id=el.dataset.manage){current=id;renderTeam();$('teamTools').scrollIntoView({behavior:'smooth',block:'start'})}else if(id=el.dataset.renameDivision){let d=db.divisions.find(x=>x.id===id);if(!d)return;let name=prompt('Division name:',d.name);if(name===null)return;name=clean(name);if(!name)return alert('Name cannot be empty.');d.name=name;save('Division updated.');render()}else if(id=el.dataset.deleteDivision){let d=db.divisions.find(x=>x.id===id);if(!d)return;let n=db.teams.filter(t=>t.division===id).length;if(n)return alert('Move or delete the '+n+' team(s) in this division first.');if(!confirm('Delete division '+d.name+'?'))return;db.divisions=db.divisions.filter(x=>x.id!==id);save('Division deleted.');render()}else if(id=el.dataset.deleteTeam){let t=db.teams.find(x=>x.id===id);if(!t||!confirm('Delete '+t.name+' and its saved roster, coaches and lineup from this device?'))return;db.teams=db.teams.filter(x=>x.id!==id);if(current===id)current='';save('Team deleted.');render()}};
$('closeTeam').onclick=()=>{current='';renderTeam();$('divisionList').scrollIntoView({behavior:'smooth',block:'start'})};
$('renameTeam').onclick=()=>{let t=team(),name=clean($('editTeamName').value);if(!t||!name)return alert('Enter a team name.');t.name=name;save('Team name saved.');render()};
$('moveTeam').onclick=()=>{let t=team();if(!t)return;t.division=$('moveDivision').value;save('Team moved.');render()};
render();
